# Website settings
url: "https://www.erikdavidtech.com"

# Internal nav
nav:
  main:
    # technology: "/technology"
    speaker: "/speaker"
    # projects: "/projects"
    writer: "/writer"
    blog: "/blog"
    # photos: "https://www.flickr.com/photos/brikis98/albums/"
  # writing:
  #   all: "/writing"
  #   popular: "/writing/popular"
  #   tags: "/writing/tags"
  #   rss: "/feed.xml"

# Bio settings
name: "Erik Gross"
description: "The home page of Erik Gross, co-founder of The Tech Academy, author of &quot;You Are Not Stupid: Computers and Technology Simplified&quot; and &quot;Learn To Code in Hours with JavaScript&quot;, and software engineer at IBM, Providence and Travelliance."
thumbnail_path: "profile-photos/ErikHeadshot.jpg"
website_repo_url: "https://github.com/kiresorg/kiresorg.github.io"
techacademy_url: "https://www.learncodinganywhere.com"
youarenotstupid_url: "http://mybook.to/youarenotstupid"
nnps_url: "https://en.wikipedia.org/wiki/Nuclear_Power_School"
youtube_url: "https://www.youtube.com/channel/UCyJ8Tpn57JR_O2xm28xkvEA"
erik_email: "mailto:erikdavidtech@gmail.com"

# URLs
contact_urls:
  twitter:
    url: "https://twitter.com/erikdavidgross"
    label: "Twitter"
    icon: "twitter-square"
    username: "@erikdavidgross"
  linkedin:
    url: "https://www.linkedin.com/in/erikgrosstechacademy"
    label: "LinkedIn"
    icon: "linkedin-square"
  facebook:
    url: "https://www.facebook.com/erik.gross.902"
    label: "Facebook"
    icon: "facebook-square"
  github:
    url: "https://github.com/kiresorg/"
    label: "GitHub"
    icon: "github-square"
  email:
    url: "mailto:erikdavidtech@gmail.com"
    label: "Email"
    value: "erikdavidtech@gmail.com"
    icon: "envelope-square"

# Jekyll build settings
paginate: 10
paginate_path: "/blog/page:num/"
permalink: "/blog/:categories/:year/:month/:day/:title.html"
sass:
  sass_dir: "/assets/css"
  style: :compressed
highlighter: rouge
timezone: 'America/Los_Angeles'
repository: kiresorg/kiresorg.github.io

# Plugins (GitHub Pages only support a few)
plugins:
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-paginate
